cluster:
    name: ${CLUSTER_NAME}

plugin.mandatory: cloud-aws

path:
  logs: /var/log
  data: /var/esdata

action.disable_delete_all_indices: true

cloud.aws:
  region: ${AWS_REGION}

discovery:
  type: ec2
  ec2:
    ping_timeout: 30s
    tag.Name: ${EC2_TAG_NAME}
    host_type: private_dns

discovery.zen:
  minimum_master_nodes: ${MASTER_NODES}
  ping_timeout: 30s
  ping:
    multicast.enabled: false
    unicast.hosts: []

script.engine.groovy.inline.update: on
script.engine.groovy.inline.aggs: on
script.engine.groovy.inline.search: on

network:
    host: _non_loopback_

http:
    host: 0.0.0.0
    compression: true

    cors:
        enabled: true
        allow-origin: '*'
