cluster:
    name: ${CLUSTER_NAME}

path:
  logs: /var/log
  data: /var/esdata

cloud.aws:
  region: ${AWS_REGION}

discovery:
  type: ec2
  ec2:
    read_timeout: 30s
    tag.Name: ${EC2_TAG_NAME}
    host_type: private_dns

discovery.zen:
  minimum_master_nodes: ${MASTER_NODES}
  ping_timeout: 30s
  ping:
    unicast.hosts: []

script.engine.groovy.inline.update: on
script.engine.groovy.inline.aggs: on
script.engine.groovy.inline.search: on

network:
    host: 0.0.0.0

http:
    host: 0.0.0.0
    compression: true

    cors:
        enabled: true
        allow-origin: '*'
